USE TSQLV5;
GO
--1
DECLARE @Context varbinary(10) = CAST ('A' as varbinary);
SET CONTEXT_INFO @Context;
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
SET LOCK_TIMEOUT -1; 

BEGIN TRAN;
	SELECT *
	FROM Sales.Orders
	WHERE orderid = 10384
ROLLBACK;